import type { Metadata } from "next";
import localFont from "next/font/local";
import './globals.css';
import Header from "@/components/common/Header/page";
import Footer from "@/components/common/Footer/page";
import Up from "@/assets/Up";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Viva Paris",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        <Header />
        {children}
        <div className="fixed flex right-6 bottom-6 z-20">
          <Up width={60} height={60} />
        </div>
        <Footer />
      </body>
    </html>
  );
}
